In [2]:
import numpy as np
np.__version__

'1.19.5'

In [9]:
np.array([1,2,3,4,5,6,7,8,9,10]) + np.ones((10), dtype=int)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [50]:
numpy_matrix = np.array([
        [1,2,3,4,5],
        [6,7,8,9,10],
        [11,12,13,14,15],
        [16,17,18,19,20],
        [21,22,23,24,25], 
])

In [51]:
numpy_matrix.mean(axis=1,  dtype=int)

array([ 3,  8, 13, 18, 23])

In [52]:
numpy_matrix.mean(axis=0,  dtype=int)

array([11, 12, 13, 14, 15])